
services:

  # ---------------------------------------------------------------
  # Servicio 1: APP (Laravel + Apache)
  # ---------------------------------------------------------------
  app:
    build: .                             
    container_name: ghc_app
    ports:
      - "8080:80"                        
    volumes:
      - .:/var/www/html                  
    depends_on:
      - db                                
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: grand_hotel_continental
      DB_USERNAME: laravel
      DB_PASSWORD: laravel1234


  # ---------------------------------------------------------------
  # Servicio 2: DB (MariaDB)
  # ---------------------------------------------------------------
  db:
    image: mariadb:10.11
    container_name: ghc_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: grand_hotel_continental
      MARIADB_USER: laravel
      MARIADB_PASSWORD: laravel1234
      MARIADB_ROOT_PASSWORD: root1234
    volumes:
      - db_data:/var/lib/mysql            
    ports:
      - "3307:3306"                       


  # ---------------------------------------------------------------
  # Servicio 3: PMA (phpMyAdmin)
  # ---------------------------------------------------------------
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ghc_pma
    restart: unless-stopped
    ports:
      - "8081:80"                        
    environment:
      PMA_HOST: db                       
      PMA_PORT: 3306
    depends_on:
      - db


volumes:
  db_data:
